### ISSUE TITLE
Pull Requests gathering broken if API rate limit is reached

### ISSUE THREAD

**Issue by acs** [MetricsGrimoire/pullpo#3]
It seems that if the gathering process is stopped because the API rate limit is reached, the pull requests are not downloaded with "updated_at" order. And next iteration, will miss pull requests because it is designed to follow an "updated_at" order.

Checked for example with: https://github.com/liferay/liferay-portal/pulls

If the 800 PRs are downloaded before API rate limit, all is ok. But if the rate limit is reached, the PRs in the database are not ordered using "updated_at" field.

**Comment by GregSutcliffe** [comment]
I'm hitting this on https://github.com/theforeman/foreman which has thousands of pull requests - I only indexed 835 before hitting the 5k limit on my API token.

Is there any update or workaround for this?

**Comment by acs** [comment]
@GregSutcliffe right now our focus in github gathering is on github backend in perceval. Maybe you can start using perceval and this backend:

https://github.com/grimoirelab/perceval

**Comment by acs** [comment]
Legacy code. Please use: https://github.com/grimoirelab/perceval
